/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import ProyectoBD.Conexion;
import java.sql.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabri
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Alumnos
     */
    Conexion auxCon = new Conexion("alumnado");
    int comprobacion=0;
    
    public VentanaPrincipal() {
        initComponents();
        DefaultTableModel modeloTabla=(DefaultTableModel) tabla.getModel();
        modeloTabla.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        panel1 = new javax.swing.JPanel();
        eTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        panel2 = new javax.swing.JPanel();
        eID = new javax.swing.JLabel();
        eNombre = new javax.swing.JLabel();
        eApellido = new javax.swing.JLabel();
        eEdad = new javax.swing.JLabel();
        eCorreo = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        tEdad = new javax.swing.JTextField();
        tApellido = new javax.swing.JTextField();
        tEmail = new javax.swing.JTextField();
        bGuardar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();
        tNIF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tBusqueda = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        bDesconexion = new javax.swing.JButton();
        bConexion = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(153, 153, 255));
        panel1.setForeground(new java.awt.Color(153, 0, 51));
        panel1.setToolTipText("");

        eTitulo.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        eTitulo.setForeground(new java.awt.Color(0, 51, 153));
        eTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eTitulo.setText("REGISTRO - DAM I");
        eTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 3));

        tabla.setBackground(new java.awt.Color(204, 204, 255));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIF/NIE", "Nombres", "Apellidos", "Edad", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
            tabla.getColumnModel().getColumn(4).setResizable(false);
        }

        panel2.setBackground(new java.awt.Color(204, 204, 255));
        panel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Alumno:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 1, 12), new java.awt.Color(0, 51, 153))); // NOI18N
        panel2.setForeground(new java.awt.Color(0, 51, 153));

        eID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eID.setForeground(new java.awt.Color(0, 51, 153));
        eID.setText("NIF/NIE");

        eNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eNombre.setForeground(new java.awt.Color(0, 51, 153));
        eNombre.setText("Nombre");

        eApellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eApellido.setForeground(new java.awt.Color(0, 51, 153));
        eApellido.setText("Apellido");

        eEdad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eEdad.setForeground(new java.awt.Color(0, 51, 153));
        eEdad.setText("Edad");

        eCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eCorreo.setForeground(new java.awt.Color(0, 51, 153));
        eCorreo.setText("Email");

        tEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEdadActionPerformed(evt);
            }
        });

        bGuardar.setText("Guardar");
        bGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bModificar.setText("Modificar");
        bModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bLimpiar.setText("Limpiar");
        bLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(bGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bLimpiar))
                            .addComponent(eID))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eNombre)
                            .addComponent(eCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(tEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tApellido)
                            .addComponent(tEmail)
                            .addComponent(tNombre)
                            .addComponent(tNIF, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(21, 21, 21))))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eID)
                    .addComponent(tNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNombre)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eApellido)
                    .addComponent(tApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eEdad)
                    .addComponent(tEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCorreo)
                    .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar)
                    .addComponent(bModificar)
                    .addComponent(bEliminar)
                    .addComponent(bLimpiar))
                .addGap(16, 16, 16))
        );

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Búsqueda Rápida (NIF/NIE):");

        bBuscar.setText("Buscar");
        bBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bDesconexion.setText("Desconexion");
        bDesconexion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bDesconexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDesconexionActionPerformed(evt);
            }
        });

        bConexion.setText("Conexion");
        bConexion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(bConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bDesconexion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(eTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(25, 25, 25))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(tBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(eTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDesconexion)
                    .addComponent(bConexion))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEdadActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        
        String nif= tNIF.getText();
        String nombre= tNombre.getText();
        String apellido= tApellido.getText();
        Integer edad= Integer.parseInt(tEdad.getText());
        String email= tEmail.getText();
        
        if(comprobacion==1){
            try{
            Connection con = auxCon.conectar();
            PreparedStatement ps=con.prepareStatement("UPDATE dam1 SET nombre=?,apellido=?,edad=?,email=? WHERE nif=?");
            
            ps.setString(1, nombre);
            ps.setString(2, apellido);
            ps.setInt(3, edad);
            ps.setString(4, email);
            ps.setString(5, nif);
            
            int verificacion = ps.executeUpdate();
            if(verificacion==0){
                JOptionPane.showMessageDialog(null, "ERROR: Alumno no encontrado ó Modificación no permitida");
            }
            else{
                JOptionPane.showMessageDialog(null, "Alumno Modificado");
            }
            limpiar();
            cargarTabla();
            } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "ERROR: No se puede realizar esta accion");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe conectarse a la Base de Datos");
        }
    }//GEN-LAST:event_bModificarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed

        String nif= tNIF.getText();
        String nombre= tNombre.getText();
        String apellido= tApellido.getText();
        Integer edad= Integer.parseInt(tEdad.getText());
        String email= tEmail.getText();
        
        if(comprobacion==1){
            try{
            Connection con = auxCon.conectar();
            PreparedStatement ps=con.prepareStatement("INSERT INTO dam1(nif,nombre,apellido,edad,email) VALUES (?,?,?,?,?)");
            
            ps.setString(1, nif);
            ps.setString(2, nombre);
            ps.setString(3, apellido);
            ps.setInt(4, edad);
            ps.setString(5, email);
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Alumno registrado");
            limpiar();
            cargarTabla();
            } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "ERROR: No se puede realizar esta accion");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe conectarse a la Base de Datos");
        }
        
        
    }//GEN-LAST:event_bGuardarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        
        if(comprobacion==1){
            try{
            int fila= tabla.getSelectedRow();
            String nif = tabla.getValueAt(fila, 0).toString();
            PreparedStatement ps;
            ResultSet rs;
            
            Connection con = auxCon.conectar();
            ps=con.prepareStatement("SELECT nombre,apellido,edad,email FROM dam1 WHERE nif=?");
            ps.setString(1, nif);
            rs=ps.executeQuery();
            
            while(rs.next()){
                tNIF.setText(nif);
                tNombre.setText(rs.getString("nombre"));
                tApellido.setText(rs.getString("apellido"));
                tEdad.setText(rs.getString("edad"));
                tEmail.setText(rs.getString("email"));
            }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
        
    }//GEN-LAST:event_tablaMouseClicked

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        
        limpiar();
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        
        String nif= tNIF.getText();
        
        if(comprobacion==1){
            try{
            Connection con = auxCon.conectar();
            PreparedStatement ps=con.prepareStatement("DELETE FROM dam1 WHERE nif=?");
            
            ps.setString(1, nif);
            
            int verificacion = ps.executeUpdate();
            if(verificacion==0){
                JOptionPane.showMessageDialog(null, "ERROR: Alumno no encontrado");
            }
            else{
                JOptionPane.showMessageDialog(null, "Alumno Eliminado");
            }
            limpiar();
            cargarTabla();
            } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "ERROR: No se puede realizar esta accion");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe conectarse a la Base de Datos");
        }
        
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        
        if(comprobacion==1){
            try{
            String nif=tBusqueda.getText();
            PreparedStatement ps;
            ResultSet rs;
            
            Connection con = auxCon.conectar();
            ps=con.prepareStatement("SELECT nombre,apellido,edad,email FROM dam1 WHERE nif=?");
            ps.setString(1, nif);
            rs=ps.executeQuery();
            
            while(rs.next()){
                //if(rs.getObject(1))
                JOptionPane.showMessageDialog(null, "Alumno encontrado!");
                tNIF.setText(nif);
                tNombre.setText(rs.getString("nombre"));
                tApellido.setText(rs.getString("apellido"));
                tEdad.setText(rs.getString("edad"));
                tEmail.setText(rs.getString("email"));
                
                tBusqueda.setText("");
            }
            }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe conectarse a la Base de Datos");
        }
        
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bDesconexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDesconexionActionPerformed
        
        auxCon.desconectar();
        JOptionPane.showMessageDialog(null, "Se ha desconectado de la Base de Datos");
        DefaultTableModel modeloTabla=(DefaultTableModel) tabla.getModel();
        modeloTabla.setRowCount(0);
        comprobacion=0;
    }//GEN-LAST:event_bDesconexionActionPerformed

    private void bConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConexionActionPerformed
        
        JOptionPane.showMessageDialog(null, "Se ha conectado a la Base de Datos");
        cargarTabla();
        comprobacion=1;
    }//GEN-LAST:event_bConexionActionPerformed

    private void limpiar(){
        tNIF.setText("");
        tNombre.setText("");
        tApellido.setText("");
        tEdad.setText("");
        tEmail.setText("");
    }
    
    private void cargarTabla(){
    DefaultTableModel modeloTabla=(DefaultTableModel) tabla.getModel();
    modeloTabla.setRowCount(0);
    
    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd;
    int columnas;
    
    try{
        Connection con = auxCon.conectar();
        ps=con.prepareStatement("SELECT nif,nombre,apellido,edad,email FROM dam1");
        rs=ps.executeQuery();
        rsmd=rs.getMetaData();
        columnas=rsmd.getColumnCount();
        
        while(rs.next()){
            Object[] fila= new Object[columnas];
            for(int i=0;i<columnas;i++){
                fila[i]=rs.getObject(i+1);
            }
            modeloTabla.addRow(fila);
        }
        
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e.toString());
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bConexion;
    private javax.swing.JButton bDesconexion;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bModificar;
    private javax.swing.JLabel eApellido;
    private javax.swing.JLabel eCorreo;
    private javax.swing.JLabel eEdad;
    private javax.swing.JLabel eID;
    private javax.swing.JLabel eNombre;
    private javax.swing.JLabel eTitulo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JTextField tApellido;
    private javax.swing.JTextField tBusqueda;
    private javax.swing.JTextField tEdad;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tNIF;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
